
    create table cuenta (
        id bigint generated by default as identity (start with 1),
        empresa varchar(255),
        periodo varchar(255),
        tipo varchar(255),
        valor numeric(19,2),
        primary key (id)
    )

    create table indicador (
        id bigint generated by default as identity (start with 1),
        formula varchar(255) not null,
        nombre varchar(255) not null,
        primary key (id)
    )

    create table metodologia (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255) not null,
        primary key (id)
    )

    create table regla (
        tipo varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        nombre varchar(255) not null,
        criterio integer,
        comparador char(255),
        valorAComparar numeric(19,2),
        indicador_id bigint,
        metodologia_id bigint,
        primary key (id)
    )

    alter table regla 
        add constraint FK_quql18jayyojunxsp81u17hxg 
        foreign key (indicador_id) 
        references indicador

    alter table regla 
        add constraint FK_owku3q9bc6f9pmo6qlvswk1my 
        foreign key (metodologia_id) 
        references metodologia
